export const trackLine = [
  {
    type: "station",
    id: 1,
    name: "A",
    numberOfTrainsOccupied: 0,
    homeSignalSection: {
      id: 4,
      length: 2,
      occupied: false,
      occupiedBy: -1,
      signalColor: "yellow",
      signalType: "section",
      signalId: 1,
    },
    outerSignalSection: {
      id: 4,
      length: 2,
      occupied: false,
      occupiedBy: -1,
      signalColor: "red",
      signalType: "section",
      signalId: 1,
    },
    mainLineSections: {
      id: 4,
      length: 10,
      occupied: false,
      occupiedBy: -1,
      signalColor: "red",
      signalType: "section",
      signalId: 1,
    },
    upLineSections: {
      id: 4,
      length: 10,
      occupied: false,
      occupiedBy: -1,
      signalColor: "red",
      signalType: "section",
      signalId: 1,
    },
    downLineSections: {
      id: 4,
      length: 10,
      occupied: false,
      occupiedBy: -1,
      signalColor: "red",
      signalType: "section",
      signalId: 1,
    },
  },
  {
    type: "block",
    id: 1,
    name: "BlockA",
    sections: [
      {
        id: 1,
        length: 14,
        occupied: false,
        occupiedBy: -1,
        signalColor: "green",
        signalType: "section",
        signalId: 1,
      },
      {
        id: 2,
        length: 14,
        occupied: false,
        occupiedBy: -1,
        signalColor: "green",
        signalType: "section",
        signalId: 1,
      },
      {
        id: 3,
        length: 14,
        occupied: false,
        occupiedBy: -1,
        signalColor: "green",
        signalType: "section",
        signalId: 1,
      },
      {
        id: 4,
        length: 14,
        occupied: false,
        occupiedBy: -1,
        signalColor: "green",
        signalType: "section",
        signalId: 1,
      },
    ],
  },
];
